services:

  postgres:
    image: postgres:16
    container_name: hexmaster_db
    environment:
      TZ: America/Los_Angeles  # Add this line
      POSTGRES_DB: hexmaster
      POSTGRES_USER: hexmaster
      POSTGRES_PASSWORD: hexmaster
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hexmaster" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hexmaster_bot:
    image: ghcr.io/garykuepper/hexmaster:main
    # build: .
    container_name: hexmaster_bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles  # Add this line
      - DATABASE_URL=postgresql+asyncpg://hexmaster:hexmaster@127.0.0.1:5432/hexmaster
      - OCR_URL=http://localhost:8000
      - WARAPI_BASE_URL=https://war-service-live.foxholeservices.com/api
    volumes:
      - shared_data:/app/shared
      # To provide your own priority templates or core data, uncomment the line below:
      # - ./data:/app/data
    network_mode: host

volumes:
  pgdata:
  shared_data:
