services:
  postgres:
    image: postgres:16
    container_name: hexmaster_db
    environment:
      POSTGRES_DB: hexmaster
      POSTGRES_USER: hexmaster
      POSTGRES_PASSWORD: hexmaster
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hexmaster"]
      interval: 5s
      timeout: 5s
      retries: 5

  fir-ocr:
    container_name: fir-ocr
    shm_size: "1gb"
    build:
      context: ../fir
      dockerfile: Dockerfile.headless
    restart: always
    environment:
      - TZ=America/Los_Angeles

  hexmaster_bot:
    build: .
    container_name: hexmaster_bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      fir-ocr:
        condition: service_started
    env_file:
      - .env
    environment:
      # This overrides the local localhost URL for internal container networking
      - DATABASE_URL=postgresql+asyncpg://hexmaster:hexmaster@postgres:5432/hexmaster
      - OCR_URL=http://fir-ocr:5000
    volumes:
      - shared_data:/app/shared

volumes:
  pgdata:
  shared_data: